1:
  sidebar_id: 1
  role_id: 1
2:
  sidebar_id: 2
  role_id: 1
3:
  sidebar_id: 3
  role_id: 1
4:
  sidebar_id: 4
  role_id: 1
5:
  sidebar_id: 5
  role_id: 1
6:
  sidebar_id: 6
  role_id: 1
7:
  sidebar_id: 7
  role_id: 1
8:
  sidebar_id: 7
  role_id: 2
9:
  sidebar_id: 7
  role_id: 3
10:
  sidebar_id: 8
  role_id: 1
11:
  sidebar_id: 8
  role_id: 2
12:
  sidebar_id: 8
  role_id: 3
13:
  sidebar_id: 9
  role_id: 1
14:
  sidebar_id: 9
  role_id: 2
15:
  sidebar_id: 10
  role_id: 1
16:
  sidebar_id: 10
  role_id: 2
17:
  sidebar_id: 11
  role_id: 1
18:
  sidebar_id: 11
  role_id: 2
19:
  sidebar_id: 12
  role_id: 1
20:
  sidebar_id: 12
  role_id: 2
21:
  sidebar_id: 13
  role_id: 1
22:
  sidebar_id: 13
  role_id: 2
23:
  sidebar_id: 14
  role_id: 1
24:
  sidebar_id: 14
  role_id: 2
25:
  sidebar_id: 15
  role_id: 1
26:
  sidebar_id: 15
  role_id: 2
27:
  sidebar_id: 16
  role_id: 1
28:
  sidebar_id: 16
  role_id: 2
29:
  sidebar_id: 17
  role_id: 1
30:
  sidebar_id: 17
  role_id: 2
31:
  sidebar_id: 18
  role_id: 1
32:
  sidebar_id: 18
  role_id: 2
33:
  sidebar_id: 19
  role_id: 1
34:
  sidebar_id: 19
  role_id: 2
35:
  sidebar_id: 20
  role_id: 1
36:
  sidebar_id: 20
  role_id: 2
37:
  sidebar_id: 21
  role_id: 1
38:
  sidebar_id: 21
  role_id: 2
39:
  sidebar_id: 22
  role_id: 1
40:
  sidebar_id: 22
  role_id: 2
41:
  sidebar_id: 23
  role_id: 1
42:
  sidebar_id: 23
  role_id: 2
