table_name: blog_attachments
table_comment: 'Merge table blogs vs files, for multiple attachments'
fields:
  blog:
    type: table_reference
    reference_table: blogs
    column_name: blog
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Blog reference.'
  attachment:
    type: file
    reference_table: files
    column_name: attachment
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: Attachment.
