table_name: product_description_attachment
table_comment: 'Contains attachment linked in product description.'
fields:
  product:
    type: table_reference
    reference_table: products
    column_name: product
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Product reference.'
  attachment:
    type: file
    reference_table: files
    column_name: attachment
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Attachment file.'
