table_name: voucher_codes
table_comment: 'Contains available voucher codes.'
fields:
  title:
    type: short_text
    length: '255'
    column_name: title
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Title of code. (Using for administration.)'
  stockcode:
    type: short_text
    length: '255'
    column_name: stockcode
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'Stockcode used for billing integration.'
  code:
    type: short_text
    length: '255'
    column_name: code
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'Code that must be entered by user on checkout.'
  type:
    type: enumarated_list
    values:
      percentage: percentage
      exact_discount: exact_discount
    column_name: type
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Type of voucher codes.'
  discount_percentage:
    type: float
    column_name: discount_percentage
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Percentage of discount that must apply when used.'
  exact_discount:
    type: float
    column_name: exact_discount
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Exact discount of code.'
  always_available:
    type: checkbox
    column_name: always_available
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'If checked no need to enter start date and end date, code is always available.'
  start_date:
    type: date
    column_name: start_date
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Code availability start date.'
  end_date:
    type: date
    column_name: end_date
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Code availability end date.'
